spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://db-mysql-shop.c5wyyem6sz0m.ap-northeast-2.rds.amazonaws.com:3306/shop?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: wonjun
    password: a66jhcnj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==